cache:
  paths:
    - /tmp/swarm-docker

before_script:
  - apt-get update -y
  - apt-get install -y software-properties-common
  - apt-get install -y python3
  - apt-get install -y python3-pip
  - apt-get install -y ssh
  - pip3 install boto3
  - pip3 install jsondiff
  - pip3 install awscli
  - pip3 install ansible
  - chmod -R 774 ansible
  - chmod -R 755 ansible/inventory.py
  - echo $SSH_PRIVATE_KEY | tr -d '\r' > ansible/keys/training-key.pem
  - chmod 600 ansible/keys/training-key.pem

deploy:demo:
  image: ubuntu:18.04
  only:
    - master
    - tags
  environment: 
    name: production
  script: 
    - ansible-playbook --version
    - ansible-galaxy collection install community.general
    - ./ansible/inventory.py
    - cd ansible && ansible-playbook playbooks/main.yml
  