cache:
  paths:
    - /tmp/swarm-docker

before_script:
  - apt-get update -y
  - apt-get install -y software-properties-common
  - apt-add-repository --yes --update ppa:ansible/ansible
  - apt-get install -y ansible
  - apt-get install -y python3
  - apt-get install -y python3-pip
  - pip3 install boto3
  - pip3 install jsondiff
  - pip3 install awscli
  - ansible-galaxy collection install community.general
  - chmod -R 774 ansible
  - chmod -R 755 ansible/inventory.py
  - echo $SSH_PRIVATE_KEY > ansible/training-key.pem
  - chmod 600 ansible/training-key.pem


deploy:demo:
  image: ubuntu:18.04
  only:
    - master
    - tags
  environment: 
    name: production
  script: 
    - ./ansible/inventory.py
    - cd ansible && ansible-playbook playbooks/main.yml
  